Models/ViewModels/EditArtViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ArtGalaxy.Models.ViewModels
{
    public class EditArtViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Title is a required field.")]
        [DisplayName("Title")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        public string Title { get; set; }

        [DisplayName("Description")]
        public string? Description { get; set; }

        public byte[]? Image { get; set; }

        [Required(ErrorMessage = "Publish status is required.")]
        public bool IsPublished { get; set; }
    }
}

Models/ViewModels/EditLiteratureViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ArtGalaxy.Models.ViewModels
{
    public class EditLiteratureViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Title is a required field.")]
        [DisplayName("Title")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 2)]
        public string Title { get; set; }

        [DisplayName("Description")]
        public string? Description { get; set; }

        [Required(ErrorMessage = "Content is a required field.")]
        [DisplayName("Content")]
        public string Content { get; set; }

        [Required(ErrorMessage = "Publish status is required.")]
        public bool IsPublished { get; set; }
    }
}

Models/ViewModels/EditStoryViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ArtWebsite.Models.ViewModels
{
    public class EditStoryViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Title is a required field.")]
        [DisplayName("Title")]
        public string Title { get; set; }

        [DisplayName("Description")]
        public string? Description { get; set; }

        [Required(ErrorMessage = "Content is a required field.")]
        [DisplayName("Content")]
        public string Content { get; set; }

        [Required(ErrorMessage = "Publish status is required.")]
        public bool IsPublished { get; set; }
    }
}

Models/ViewModels/PortfolioViewModel.cs
namespace ArtGalaxy.Models.ViewModels
{
    public class PortfolioViewModel
    {
        public List<Artwork> Artworks { get; set; }
        public List<Literature> Stories { get; set; }

        public string PortfolioDisplayName { get; set; }

        public bool IsSelf { get; set; }

        public string StatusMessage { get; set; }
    }
}

Controllers/PortfolioController.cs
using ArtGalaxy.Data;
using ArtGalaxy.Models;
using ArtGalaxy.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ArtGalaxy.Controllers
{
    public class PortfolioController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<User> _userManager;

        public PortfolioController(ApplicationDbContext db, UserManager<User> userManager)
        {
            _db = db;
            _userManager = userManager; 
        }

        public async Task<IActionResult> Index(string name)
        {
            var existingUser = _db.Users.Where(u => u.DisplayName == name);

            //If user does not exist, go back to home page 
            if (!existingUser.Any())
                return LocalRedirect("/Home");

            var user = await _userManager.GetUserAsync(User);

            //If user is accessing their own portfolio, load all items. Else, only load published items
            List<Artwork> artworks = new List<Artwork>();
            List<Literature> stories = new List<Literature>();
            bool isSelf = false;

            if(user != null && name == user.DisplayName)
            {
                artworks = _db.Artworks
                    .Where(a => a.User.Id == user.Id)
                    .ToList();

                stories = _db.Stories
                    .Where(s => s.User.Id == user.Id)
                    .ToList();

                isSelf = true;
            }
            else
            {
                artworks = _db.Artworks
                    .Where(a => a.User.DisplayName == name && a.isPublished)
                    .ToList();

                stories = _db.Stories
                    .Where(s => s.User.DisplayName == name && s.isPublished)
                    .ToList();
            }


            var viewModel = new PortfolioViewModel { Artworks = artworks, Stories = stories, 
                PortfolioDisplayName = name, IsSelf = isSelf };

            viewModel.StatusMessage = TempData["StatusMessage"] as string;

            return View(viewModel);
        }

        public async Task<IActionResult> View(string type, int id)
        {
            ViewData["Type"] = type;
            ViewData["Id"] = id;

            DisplayViewModel viewModel = new DisplayViewModel();

            bool isLiked = false;
            
            if(type == "Art" || type == "art")
            {
                var content = await _db.Artworks
                    .Include(a => a.User)
                    .Include(a => a.Comments)
                    .FirstOrDefaultAsync(a => a.Id == id);

                viewModel.Content = content;

                if (viewModel.Content == null)
                    return LocalRedirect("/Home");

                //await LoadReplies(content.Comments);

                viewModel.Type = "Artwork";
                viewModel.Image = content.Image;

                var user = await _userManager.GetUserAsync(User);

                //Check if liked
                if(user != null)
                {
                    isLiked = _db.Likes.Any(l => l.User.Id == user.Id && l.Artwork.Id == id);
                }

                //Increase view count
                if (user != null && user.Id != viewModel.Content.User.Id)
                {
                    // Use a unique key to store whether the user has viewed this content
                    var viewKey = $"{type}-{id}-Viewed-{user.Id}";

                    // Check if the user has not viewed this content
                    if (!HttpContext.Request.Cookies.ContainsKey(viewKey))
                    {
                        // Increment the view count
                        viewModel.Content.Views++;
                        await _db.SaveChangesAsync();

                        // Set a cookie to track that the user has viewed this content
                        HttpContext.Response.Cookies.Append(viewKey, "true", new CookieOptions
                        {
                            Expires = DateTime.Now.AddMinutes(5) // Set the expiration as needed
                        });
                    }
                }


            }
            else if (type == "Literature" || type == "literature")
            {
                var content = await _db.Stories
                    .Include(s => s.User)
                    .Include(s => s.Comments)
                    .FirstOrDefaultAsync(s => s.Id == id);

                viewModel.Content = content;

                var user = await _userManager.GetUserAsync(User);

                if (viewModel.Content == null)
                    return LocalRedirect("/Home");

                //await LoadReplies(content.Comments);

                viewModel.Type = "Literature";
                viewModel.LiteratureContent = content.Content;
                viewModel.ReadingTime = content.ReadingTime;

                //Check if liked
                if (user != null)
                {
                    isLiked = _db.Likes.Any(l => l.User.Id == user.Id && l.Literature.Id == id);
                }

                //Increase view count
                if (user != null && user.Id != viewModel.Content.User.Id)
                {
                    // Use a unique key to store whether the user has viewed this content
                    var viewKey = $"{type}-{id}-Viewed-{user.Id}";

                    // Check if the user has not viewed this content
                    if (!HttpContext.Request.Cookies.ContainsKey(viewKey))
                    {
                        // Increment the view count
                        viewModel.Content.Views++;
                        await _db.SaveChangesAsync();

                        // Set a cookie to track that the user has viewed this content
                        HttpContext.Response.Cookies.Append(viewKey, "true", new CookieOptions
                        {
                            Expires = DateTime.Now.AddMinutes(5) // Set the expiration as needed
                        });
                    }
                }


                if (viewModel.Content == null)
                    return LocalRedirect("/Home");
            }

            viewModel.StatusMessage = TempData["StatusMessage"] as string;
            viewModel.IsLiked = isLiked;

            return View(viewModel);
        }

        private async Task LoadReplies(IEnumerable<Comment> comments)
        {
            foreach (Comment comment in comments)
            {
                await _db.Entry(comment)
                    .Collection(c => c.Replies)
                    .Query()
                    .Include(r => r.User) // Include the user for each reply
                    .LoadAsync();

                // Recursively load replies for this comment
                await LoadReplies(comment.Replies);
            }
        }

        public async Task<IActionResult> EditArtwork(int id)
        {
            if(!User.Identity.IsAuthenticated)
            {
                TempData["StatusMessage"] = "You need to be logged in to perform that action.";
                return LocalRedirect("/Identity/Account/Login");
            }

            var artwork = await _db.Artworks
                .Include(a => a.User)
                .FirstOrDefaultAsync(a => a.Id == id);


            //If art doesn't exist, exit page
            if (artwork == null)
                return RedirectToAction("Index");


            //If user didn't upload the art, exit page
            var user = await _userManager.GetUserAsync(User);
            if(artwork.User.Id != user.Id)
            {
                return RedirectToAction("Index");
            }

            var viewModel = new EditArtViewModel {
                Id = artwork.Id,
                Title = artwork.Title,
                Description = artwork.Description,
                Image = artwork.Image,
                IsPublished = artwork.isPublished
            };

            return View(viewModel);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditArt(EditArtViewModel viewModel)
        {

            if (viewModel.Id == 0)
                return RedirectToAction("Index");

            // Check if ModelState is valid
            if (ModelState.IsValid)
            {
                

                // Retrieve the existing artwork from the database
                var existingArtwork = await _db.Artworks.FindAsync(viewModel.Id);

                // Check if the artwork exists
                if (existingArtwork != null)
                {
                    // Update properties of the existing artwork
                    existingArtwork.Title = viewModel.Title.Trim('\n', '\r');

                    if(!string.IsNullOrEmpty(viewModel.Description))
                        existingArtwork.Description = viewModel.Description.Trim('\n', '\r');

                    existingArtwork.isPublished = (bool) viewModel.IsPublished;

                    // Save changes to the database
                    await _db.SaveChangesAsync();

                    TempData["StatusMessage"] = "Your changes were saved.";

                    // Redirect to the appropriate View page after successful update
                    return RedirectToAction("View", new { type = "Art", id = existingArtwork.Id });
                }
            }

            // If ModelState is not valid or the artwork doesn't exist, return to the edit page
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditLiterature(int id)
        {
            var literature = await _db.Stories.FirstOrDefaultAsync(s => s.Id == id);

            //If literature doesn't exist, exit page
            if (literature == null)
                return RedirectToAction("Index");

            //If user didn't upload the literature, exit page

Views/Portfolio/EditArt.cshtml
@model ArtWebsite.Models.ViewModels.EditArtViewModel

@{
    ViewData["Title"] = "Edit Art";
}

<style>
    img {
        max-width: 50vw;
        max-height: 40vh;
    }
</style>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    function confirmDelete(type) {
        // Display a loading spinner or any indication of processing
        // (Optional: you can use a library like SweetAlert for better UI/UX)

        var id = '@Model.Id';

        // Make an AJAX request to the Delete action in your PortfolioController
        $.ajax({
            url: '@Url.Action("Delete", "Portfolio")', // Adjust the URL based on your project's routing
            type: 'POST', // Or 'GET' depending on your controller method
            data: { id: id,
                    type: type }, // Pass the ID or any other necessary data
            success: function (result) {
                // Handle success - close the modal, update UI, etc.
                $('#deleteConfirmationModal').modal('hide');

                // Redirect to a different page after successful deletion
                window.location.href = '@Url.Action("Index", "Portfolio")'; // Adjust the URL as needed
            },
            error: function (error) {
                // Handle error - display an error message, log, etc.
                console.error('Error deleting artwork:', error);
            }
        });
    }
</script>

<h1>Edit Art</h1>

<div class="row">
    <div class="col-md-4">


        <form asp-action="EditArt" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-floating">
                <label asp-for="Title" class="form-text"></label>
                <div class="mb-3">
                    <input asp-for="Title" class="form-control" style="height:4.5em; padding-top:1.5rem" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            
            </div>
        

            <div class="form-floating">
                <label asp-for="Description" class="form-text"></label>
            
                <div class="mb-3"> 
                    <textarea asp-for="Description" class="form-control" style="padding-top:2rem" ></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <br />

            <!--IMAGE CODE-->
            @{
                    <p><i>Note: the image cannot be changed</i></p>
                var base64Image = Convert.ToBase64String(Model.Image); 
                    <img src="data:image/jpeg;base64, @base64Image" alt="Image" class="image"/>
            }

            <br />

            <fieldset class="form-group">
              <legend class="mt-4">Do you want to publish this art?</legend>

              <div class="form-check">
                  @Html.RadioButtonFor(m => m.IsPublished, true, 
                      new { @id = "", @class="form-check-input", @checked="true" })

                  @Html.LabelFor(m => m.IsPublished, "Yes, publish", new { @class="form-check-label" })
              </div>
          

              <div class="form-check">
                  @Html.RadioButtonFor(m => m.IsPublished, false, 
                      new { @id = "", @class="form-check-input" })

                  @Html.LabelFor(m => m.IsPublished, "No, don't publish", new { @class="form-check-label" })
              </div> 
            </fieldset>

            <br />

            <div class="form-floating">
                <input type="submit" value="Save Changes" class="btn btn-primary" />
            </div>

         
        </form>

        
    </div>

    @*Delete button*@
    <div class="form-floating text-end mt-2">
        <button id="deleteButton" type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">Delete</button>
    </div>
</div>

@*Delete Confirmation Modal*@
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete the art "@Model.Title"? This can't be undone!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button id="confirmDeleteButton" type="button" class="btn btn-danger" onclick="confirmDelete('art')">Delete</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Portfolio/EditArtwork.cshtml
@model ArtGalaxy.Models.ViewModels.EditArtViewModel

@{
    ViewData["Title"] = "Edit Art";
}

<style>
    img {
        max-width: 50vw;
        max-height: 40vh;
    }
</style>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    function confirmDelete(type) {
        // Display a loading spinner or any indication of processing
        // (Optional: you can use a library like SweetAlert for better UI/UX)

        var id = '@Model.Id';

        // Make an AJAX request to the Delete action in your PortfolioController
        $.ajax({
            url: '@Url.Action("Delete", "Portfolio")', // Adjust the URL based on your project's routing
            type: 'POST', // Or 'GET' depending on your controller method
            data: { id: id,
                    type: type }, // Pass the ID or any other necessary data
            success: function (result) {
                // Handle success - close the modal, update UI, etc.
                $('#deleteConfirmationModal').modal('hide');

                // Redirect to a different page after successful deletion
                window.location.href = '@Url.Action("Index", "Portfolio")'; // Adjust the URL as needed
            },
            error: function (error) {
                // Handle error - display an error message, log, etc.
                console.error('Error deleting artwork:', error);
            }
        });
    }
</script>

<h1>Edit Art</h1>

<div class="row">
    <div class="col-md-4">


        <form asp-action="EditArt" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-floating">
                <label asp-for="Title" class="form-text"></label>
                <div class="mb-3">
                    <input asp-for="Title" class="form-control" style="height:4.5em; padding-top:1.5rem" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            
            </div>
        

            <div class="form-floating">
                <label asp-for="Description" class="form-text"></label>
            
                <div class="mb-3"> 
                    <textarea asp-for="Description" class="form-control" style="padding-top:2rem" ></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <br />

            <!--IMAGE CODE-->
            @{
                    <p><i>Note: the image cannot be changed</i></p>
                var base64Image = Convert.ToBase64String(Model.Image); 
                    <img src="data:image/jpeg;base64, @base64Image" alt="Image" class="image"/>
            }

            <br />

            <fieldset class="form-group">
              <legend class="mt-4">Do you want to publish this art?</legend>

              <div class="form-check">
                  @Html.RadioButtonFor(m => m.IsPublished, true, 
                      new { @id = "", @class="form-check-input", @checked="true" })

                  @Html.LabelFor(m => m.IsPublished, "Yes, publish", new { @class="form-check-label" })
              </div>
          

              <div class="form-check">
                  @Html.RadioButtonFor(m => m.IsPublished, false, 
                      new { @id = "", @class="form-check-input" })

                  @Html.LabelFor(m => m.IsPublished, "No, don't publish", new { @class="form-check-label" })
              </div> 
            </fieldset>

            <br />

            @*Cancel and submit buttons*@
            <div class="form-floating">
                <button class="btn btn-secondary" onclick="location.href='View/Art/@Model.Id';">Cancel</button>
                <input type="submit" value="Save Changes" class="btn btn-primary" style="margin-left: 10px;" />
            </div>

         
        </form>

        
    </div>

    @*Delete button*@
    <div class="form-floating text-end mt-2">
        <button id="deleteButton" type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">Delete</button>
    </div>
</div>

@*Delete Confirmation Modal*@
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete the art "@Model.Title"? This can't be undone!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" style="background-color: #2e373f" data-bs-dismiss="modal">Cancel</button>
                <button id="confirmDeleteButton" type="button" class="btn btn-danger" onclick="confirmDelete('art')">Delete</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Portfolio/EditLiterature.cshtml
@model ArtGalaxy.Models.ViewModels.EditLiteratureViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Edit Literature";
}

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    function confirmDelete(type) {
        // Display a loading spinner or any indication of processing
        // (Optional: you can use a library like SweetAlert for better UI/UX)

        var id = '@Model.Id';

        // Make an AJAX request to the Delete action in your PortfolioController
        $.ajax({
            url: '@Url.Action("Delete", "Portfolio")', // Adjust the URL based on your project's routing
            type: 'POST', // Or 'GET' depending on your controller method
            data: { id: id,
                    type: type }, // Pass the ID or any other necessary data
            success: function (result) {
                // Handle success - close the modal, update UI, etc.
                $('#deleteConfirmationModal').modal('hide');

                // Redirect to a different page after successful deletion
                window.location.href = '@Url.Action("Index", "Portfolio")'; // Adjust the URL as needed
            },
            error: function (error) {
                // Handle error - display an error message, log, etc.
                console.error('Error deleting artwork:', error);
            }
        });
    }
</script>

<h1>Edit Literature</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="EditLiterature" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="Id" />

            <div class="form-floating">
                <label asp-for="Title" class="form-text"></label>
                <div class="mb-3">
                    <input asp-for="Title" class="form-control" style="height:4.5em; padding-top:1.5rem"/>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>


            <div class="form-floating">
                <label asp-for="Description" class="form-text"></label>

                <div class="mb-3">
                    <textarea asp-for="Description" class="form-control" style="padding-top:2rem"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="form-floating">
                <label asp-for="Content" class="form-text"></label>

                <div class="mb-3">
                    <textarea asp-for="Content" class="form-control" style="padding-top:2rem" 
                        placeholder="Copy and paste or type your literature here..."></textarea>
                    <span asp-validation-for="Content" class="text-danger"></span>
                </div>
            </div>

            <fieldset class="form-group">
                <legend class="mt-4">Do you want to publish this literature?</legend>

                <div class="form-check">
                    @Html.RadioButtonFor(m => m.IsPublished, true, 
                        new { @id = "", @class="form-check-input", @checked="true" })

                    @Html.LabelFor(m => m.IsPublished, "Yes, publish", new { @class="form-check-label" })
                </div>


                <div class="form-check">
                    @Html.RadioButtonFor(m => m.IsPublished, false, 
                        new { @id = "", @class="form-check-input" })

                    @Html.LabelFor(m => m.IsPublished, "No, don't publish", new { @class="form-check-label" })
                </div>
            </fieldset>

            <br />

            @*Cancel and submit buttons*@
            <div class="form-floating">
                <button class="btn btn-secondary" onclick="location.href='View/Literature/@Model.Id';">Cancel</button>
                <input type="submit" value="Save Changes" class="btn btn-primary" style="margin-left: 10px;" />
            </div>
        </form>
    </div>

    @*Delete button*@
    <div class="form-floating text-end mt-2">
        <button id="deleteButton" type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteConfirmationModal">Delete</button>
    </div>
</div>

@*Delete Confirmation Modal*@
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Deletion</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete the literature "@Model.Title"? This can't be undone!
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button id="confirmDeleteButton" type="button" class="btn btn-danger" onclick="confirmDelete('literature')">Delete</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}